local_service/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

app_name = 'mainapp'

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', views.home, name='home'),
   path('about/', views.about, name='about'),
   path('login/', views.login, name='login'),
   path('register/', views.register, name='register'),
   path("service/", views.service, name='service'),
   path('providerdetails/<str:provider_slug>/',views.providerdetails,name="providerdetails"),
   path('dashboard/',views.dashboard,name="dashboard"),
   path('customer/profile/',views.CustomerProfile,name='CustomerProfile'),
   path('provider/profile/',views.ProviderProfile,name='ProviderProfile'),
   path('changepassword/', views.changepassword, name='changepassword'),
   path('customer/profile/edit/', views.CustomerProfileEdit, name='CustomerProfileEdit'),
   path('provider/profile/edit/', views.ProviderProfileEdit, name='ProviderProfileEdit'),
   path('logout/', views.logout, name='logout'),
   path('service/booking/<str:provider_slug>/', views.service_booking, name='service_booking'),
   path('add_previous_work/', views.Add_previous_work, name='Add_previous_work'),
   path('booking/status/update/<int:booking_id>/<str:action>/', views.update_booking_status, name='update_booking_status'),
   path('booking/review/<int:booking_id>/', views.booking_review, name='booking_review'),
   path('rewrite_booking_review/<int:review_id>/', views.rewrite_booking_review, name='rewrite_booking_review'),
   path('previous_work/edit/<int:work_id>/', views.previous_work_Edit, name='previous_work_Edit'),
   path('previous_work/delete/<int:work_id>/', views.previous_work_delete, name='previous_work_delete'),
   path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/views.py
from urllib import request
from django.contrib import messages
from django.shortcuts import render ,redirect, get_object_or_404
from .forms import ChangePasswordForm, CustomerProfileForm, PreviousWorkForm, RegisterForm, LoginForm, ProviderProfileForm, ServiceFilterForm,bookingForm, bookingReviewForm 
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate , login as auth_login, logout as auth_logout  
from django.contrib.auth.decorators import login_required
from .models import All_User, CustomerProfileModel, ProviderProfileModel, Previous_Work, Booking , BookingReviews, AverageRating
from django.db.models import Q , Avg
from django.core.paginator import Paginator
# Create your views here.
def home(request):
       return render(request, 'myapp/home.html')

def about(request):
       return render(request, 'myapp/about.html')

def login(request):
       if request.method == 'POST':
              form = LoginForm(request.POST)
              if form.is_valid():
                     username = form.cleaned_data['username']
                     password = form.cleaned_data['password'].strip()
                     user = authenticate(username=username, password=password)
                     if user is not None:
                          auth_login(request, user)
                          return redirect('mainapp:dashboard')
       else:
              form = LoginForm()

       return render(request, 'myapp/login.html', context={'form': form})

def register(request):
       if request.method == 'POST':
             
              form = RegisterForm(request.POST)
              if form.is_valid():
                     user= form.save(commit=False)
                     password= form.cleaned_data['password'].strip()
                     user.set_password(password)
                     if form.cleaned_data['user_role']== 'service_provider':
                          user.is_service_provider = True
                     else:
                          user.is_customer = True
                     user.save()
                     return redirect('mainapp:login')
       else:
              form = RegisterForm()
       return render(request,'myapp/register.html', context={'form': form})

def logout(request):
       auth_logout(request)
       return redirect('mainapp:home')

def service(request):
       service_list= ProviderProfileModel.objects.all()
       paginator = Paginator(service_list, 4)  # Show 4 services per page
       page_number = request.GET.get('page')
       page_obj = paginator.get_page(page_number)
       form = ServiceFilterForm()
       filter_items = {}
       if request.method == 'GET':
              form = ServiceFilterForm(request.GET)
              print("GET request received with filters:", request.GET)
              
              if form.is_valid():
                     location = form.cleaned_data.get('location')
                     category = form.cleaned_data.get('category')
                     rating = form.cleaned_data.get('rating')
                     filters = Q()
                     location = location.strip()
                     if location:
                            filters &= (Q(city__iexact=location ) | Q(district__icontains=location))
                     if category:
                            print("Category filter applied:", category)
                            filters &= Q(service_name__icontains=category)
                     if rating:
                            filters &= Q(average_rating__rating__gte=float(rating))
                     if filters:
                            service_list = service_list.filter(filters)
                            paginator = Paginator(service_list, 4)  # Show 4 services per page
                            page_number = request.GET.get('page')
                            page_obj = paginator.get_page(page_number)
                            filter_items = {
                                'location': location,
                                'category': category,
                                'rating': rating
                            }
       return render(request,'myapp/service.html', context={'page_obj': page_obj , 'form': form, 'filter_items': filter_items})


def providerdetails(request, provider_slug):
       provider = ProviderProfileModel.objects.filter(slug=provider_slug).first()
       service_choices = Booking.SERVICE_TYPE_CHOICES
       previous_work = Previous_Work.objects.filter(service_provider=provider)
       rating= AverageRating.objects.filter(service_provider=provider).first()
       return render (request,"myapp/providerdetails.html", context={'provider': provider, 'service_choices': service_choices, 'previous_work': previous_work, 'rating': rating})


def dashboard(request):
       if request.user.is_authenticated:
              if request.user.is_service_provider:
                     profile = ProviderProfileModel.objects.filter(user=request.user).first()
                     bookings = Booking.objects.filter(service_provider=profile).select_related('customer')
                     upcoming_booking = bookings.filter(status__in=('pending','accept')).order_by('-booking_date')
                     history = bookings.filter(status__in=('complete','cancelled','reject')).order_by('-booking_date')
                     completed = bookings.filter(status='complete')
                     rating = completed.aggregate(avg_rating=Avg('reviews__rating'))['avg_rating']
                     rejected = bookings.filter(status='reject').count()
                     previous_work = Previous_Work.objects.filter(service_provider=profile)
                     if rating is not None:
                            rating = round(rating, 1)
                     booking_reviews = BookingReviews.objects.filter(service_provider=profile)
                     return render(request, 'myapp/provider_dashboard.html', context={'user': request.user, 'profile': profile, 'all_bookings': bookings, 'upcoming_booking': upcoming_booking, 'history': history , 'booking_reviews': booking_reviews, 'rating': rating , 'rejected': rejected, 'completed': completed, 'previous_work': previous_work    })
              elif request.user.is_customer:
                     profile = CustomerProfileModel.objects.filter(user=request.user).first()
                     bookings = Booking.objects.filter(customer=profile).select_related('service_provider')
                     upcoming_booking = bookings.filter(status__in=('pending', 'accept')).order_by('-booking_date')
                     history = bookings.filter(status__in=('complete','cancel','reject')).order_by('-booking_date')
                     booking_reviews = BookingReviews.objects.filter(customer=profile)
                     completed = bookings.filter(status='complete').count()
                     canceled = bookings.filter(status='cancel').count()
                     return render(request, 'myapp/customer_dashboard.html', context={ 'user': request.user, 'profile':profile ,'all_bookings': bookings, 'upcoming_booking': upcoming_booking, 'history': history, 'booking_reviews': booking_reviews, 'completed': completed, 'canceled': canceled})

       else:
              return redirect('mainapp:login')
       
@login_required
def CustomerProfile(request):
       print('CustomerProfile view accessed')
       CustomerProfile=CustomerProfileModel.objects.filter(user=request.user).first()
       print(CustomerProfile)
       if CustomerProfile is None:
              return redirect('mainapp:CustomerProfileEdit')
       return render (request ,'myapp/CustomerProfile.html', context={'profile': CustomerProfile , 'user': request.user})

@login_required
def ProviderProfile(request):
       print('ProviderProfile view accessed')
       ProviderProfile=ProviderProfileModel.objects.filter(user=request.user).first()
       if ProviderProfile is None:
              return redirect('mainapp:ProviderProfileEdit')  
       return render (request ,'myapp/ProviderProfile.html', context={'profile': ProviderProfile , 'user': request.user})


@login_required
def CustomerProfileEdit(request):
       profile ,created=CustomerProfileModel.objects.get_or_create(user=request.user)
       if request.method == 'POST':
              form = CustomerProfileForm(request.POST, request.FILES, instance=profile ,user=request.user)
              if form.is_valid():
                     profile.save()
                     if created:
                             messages.success(request, "Profile created successfully")
                     else:
                             messages.success(request, "Profile updated successfully")
                     return redirect('mainapp:CustomerProfile')
       else:
              form = CustomerProfileForm(instance=profile, user=request.user)
       return render(request, 'myapp/CustomerProfileEdit.html', context={'form': form ,'profile': profile })

@login_required
def ProviderProfileEdit(request):
       profile ,created=ProviderProfileModel.objects.get_or_create(user=request.user)
       if request.method == 'POST':
              form = ProviderProfileForm(request.POST, request.FILES, instance=profile ,user=request.user)
              if form.is_valid():
                     profile.save()
                     if created:
                             messages.success(request, "Profile created successfully")
                     else:
                             messages.success(request, "Profile updated successfully")
                     return redirect('mainapp:ProviderProfile')
       else:
              form = ProviderProfileForm(instance=profile, user=request.user)
       return render(request, 'myapp/ProviderProfileEdit.html', context={'form': form ,'profile': profile })


@login_required
def changepassword(request):
       if request.method == 'POST':
              form = ChangePasswordForm(request.POST, user=request.user)

myapp/templates/myapp/include/error.html
<section class="d-flex justify-content-center">
  <div>
    {% for field in form %} {% if field.errors %}
    <!-- Display field-specific errors -->
    {% for error in field.errors%}
    <strong>{{ field.label }}:</strong>
    <span class="text-danger">{{ error }}</span><br />
    {% endfor %} {% endif %} {% endfor %}
  </div>
  <!-- Display non-field errors and messages -->
  {% if form.non_field_errors %}
  <div class="alert alert-danger">
    {% for error in form.non_field_errors %}
    <span class="text-danger">{{ error }}</span><br />
    {% endfor %}
  </div>
  {% endif %}
  
</section>

myapp/templates/myapp/include/footer.html
<footer class="container-fluid bg-light py-4 pt-5">
  <div class="container">
    <div class="row text-center text-md-start">
      <div class="col-md-4 mb-4">
        <h5>Follow Us</h5>
        <ul class="list-unstyled social-media-links">
          <li>
            <a href="https://www.facebook.com" target="_blank">Facebook</a>
          </li>
          <li><a href="https://www.twitter.com" target="_blank">Twitter</a></li>
          <li>
            <a href="https://www.instagram.com" target="_blank">Instagram</a>
          </li>
          <li>
            <a href="https://www.linkedin.com" target="_blank">LinkedIn</a>
          </li>
        </ul>
      </div>

      <div class="col-md-4 mb-4">
        <h5>Contact Us</h5>
        <ul class="list-unstyled contact-info">
          <li>
            Email:
            <a href="mailto:info@localservices.com">info@localservices.com</a>
          </li>
          <li>Phone: +91-9876543210</li>
          <li>Address: 123, Chennai, India</li>
        </ul>
      </div>

      <div class="col-md-4 mb-4">
        <h5>Quick Links</h5>
        <ul class="list-unstyled quick-links">
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
      </div>
    </div>
    <div class="text-center text-muted mt-3">
      &copy; 2025 LocalService. All Rights Reserved.
    </div>
  </div>
</footer>

myapp/templates/myapp/include/header.html
<header class="container-fluid p-0">
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light px-3 shadow fixed-top"
  >
    <div class="container">
      <a href="{% url 'mainapp:home' %}" class="navbar-brand">Local Service</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="{% url 'mainapp:about' %}" class="nav-link">About</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'mainapp:service' %}" class="nav-link">Service</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'mainapp:dashboard' %}" class="nav-link"
              >Dashboard</a
            >
          </li>
          {% if user.is_service_provider %}
          <li class="nav-item d-block d-lg-none">
            <a href="{% url 'mainapp:ProviderProfile' %}" class="nav-link">Profile</a>
          </li>
          {% elif user.is_customer %}
          <li class="nav-item d-block d-lg-none">
            <a href="{% url 'mainapp:CustomerProfile' %}" class="nav-link">Profile</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'mainapp:logout' %}" class="nav-link">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'mainapp:login' %}" class="nav-link">Login</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'mainapp:register' %}" class="nav-link">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

myapp/templates/myapp/include/message.html
<div class="modal fade" id="messageModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="true" data-bs-keyboard="true" >
  <div class="modal-dialog">
    <div class='modal-content'>
      <div class="modal-body text-center">
        {% for message in messages %}
          {% if message.tags == 'error' %}
            <h5 class="alert alert-danger" role="alert">{{ message }}</h5>
          {% elif message.tags == 'success' %}
            <h5 class="alert alert-success" role="alert">{{ message }}</h5>
          {% else %}
            <h5 class="alert alert-info" role="alert">{{ message }}</h5>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% if messages %}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var messageModal = new bootstrap.Modal(
      document.getElementById("messageModal")
    );
    messageModal.show();
    setTimeout(function() {
      messageModal.hide();
    }, 1500);
  });
</script>
{% endif %}