local_service/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

app_name = 'mainapp'

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', views.home, name='home'),
   path('about/', views.about, name='about'),
   path('login/', views.login, name='login'),
   path('register/', views.register, name='register'),
   path("service/", views.service, name='service'),
   path('providerdetails/<str:provider_slug>/',views.providerdetails,name="providerdetails"),
   path('dashboard/',views.dashboard,name="dashboard"),
   path('customer/profile/',views.CustomerProfile,name='CustomerProfile'),
   path('provider/profile/',views.ProviderProfile,name='ProviderProfile'),
   path('changepassword/', views.changepassword, name='changepassword'),
   path('customer/profile/edit/', views.CustomerProfileEdit, name='CustomerProfileEdit'),
   path('provider/profile/edit/', views.ProviderProfileEdit, name='ProviderProfileEdit'),
   path('logout/', views.logout, name='logout'),
   path('service/booking/<str:provider_slug>/', views.service_booking, name='service_booking'),
   path('add_previous_work/', views.Add_previous_work, name='Add_previous_work'),
   path('booking/status/update/<int:booking_id>/<str:action>/', views.update_booking_status, name='update_booking_status'),
   path('booking/review/<int:booking_id>/', views.booking_review, name='booking_review'),
   path('rewrite_booking_review/<int:review_id>/', views.rewrite_booking_review, name='rewrite_booking_review'),
   path('previous_work/edit/<int:work_id>/', views.previous_work_Edit, name='previous_work_Edit'),
   path('previous_work/delete/<int:work_id>/', views.previous_work_delete, name='previous_work_delete'),
   path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/views.py
from urllib import request
from django.contrib import messages
from django.shortcuts import render ,redirect, get_object_or_404
from .forms import ChangePasswordForm, CustomerProfileForm, PreviousWorkForm, RegisterForm, LoginForm, ProviderProfileForm, ServiceFilterForm,bookingForm, bookingReviewForm 
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate , login as auth_login, logout as auth_logout  
from django.contrib.auth.decorators import login_required
from .models import All_User, CustomerProfileModel, ProviderProfileModel, Previous_Work, Booking , BookingReviews, AverageRating
from django.db.models import Q , Avg
from django.core.paginator import Paginator
# Create your views here.
def home(request):
       return render(request, 'myapp/home.html')

def about(request):
       return render(request, 'myapp/about.html')

def login(request):
       if request.method == 'POST':
              form = LoginForm(request.POST)
              if form.is_valid():
                     username = form.cleaned_data['username']
                     password = form.cleaned_data['password'].strip()
                     user = authenticate(username=username, password=password)
                     if user is not None:
                          auth_login(request, user)
                          return redirect('mainapp:dashboard')
       else:
              form = LoginForm()

       return render(request, 'myapp/login.html', context={'form': form})

def register(request):
       if request.method == 'POST':
             
              form = RegisterForm(request.POST)
              if form.is_valid():
                     user= form.save(commit=False)
                     password= form.cleaned_data['password'].strip()
                     user.set_password(password)
                     if form.cleaned_data['user_role']== 'service_provider':
                          user.is_service_provider = True
                     else:
                          user.is_customer = True
                     user.save()
                     return redirect('mainapp:login')
       else:
              form = RegisterForm()
       return render(request,'myapp/register.html', context={'form': form})

def logout(request):
       auth_logout(request)
       return redirect('mainapp:home')

def service(request):
       service_list= ProviderProfileModel.objects.all()
       paginator = Paginator(service_list, 4)  # Show 4 services per page
       page_number = request.GET.get('page')
       page_obj = paginator.get_page(page_number)
       form = ServiceFilterForm()
       filter_items = {}
       if request.method == 'GET':
              form = ServiceFilterForm(request.GET)
              print("GET request received with filters:", request.GET)
              
              if form.is_valid():
                     location = form.cleaned_data.get('location')
                     category = form.cleaned_data.get('category')
                     rating = form.cleaned_data.get('rating')
                     filters = Q()
                     location = location.strip()
                     if location:
                            filters &= (Q(city__iexact=location ) | Q(district__icontains=location))
                     if category:
                            print("Category filter applied:", category)
                            filters &= Q(service_name__icontains=category)
                     if rating:
                            filters &= Q(average_rating__rating__gte=float(rating))
                     if filters:
                            service_list = service_list.filter(filters)
                            paginator = Paginator(service_list, 4)  # Show 4 services per page
                            page_number = request.GET.get('page')
                            page_obj = paginator.get_page(page_number)
                            filter_items = {
                                'location': location,
                                'category': category,
                                'rating': rating
                            }
       return render(request,'myapp/service.html', context={'page_obj': page_obj , 'form': form, 'filter_items': filter_items})


def providerdetails(request, provider_slug):
       provider = ProviderProfileModel.objects.filter(slug=provider_slug).first()
       service_choices = Booking.SERVICE_TYPE_CHOICES
       previous_work = Previous_Work.objects.filter(service_provider=provider)
       rating= AverageRating.objects.filter(service_provider=provider).first()
       return render (request,"myapp/providerdetails.html", context={'provider': provider, 'service_choices': service_choices, 'previous_work': previous_work, 'rating': rating})


def dashboard(request):
       if request.user.is_authenticated:
              if request.user.is_service_provider:
                     profile = ProviderProfileModel.objects.filter(user=request.user).first()
                     bookings = Booking.objects.filter(service_provider=profile).select_related('customer')
                     upcoming_booking = bookings.filter(status__in=('pending','accept')).order_by('-booking_date')
                     history = bookings.filter(status__in=('complete','cancelled','reject')).order_by('-booking_date')
                     completed = bookings.filter(status='complete')
                     rating = completed.aggregate(avg_rating=Avg('reviews__rating'))['avg_rating']
                     rejected = bookings.filter(status='reject').count()
                     previous_work = Previous_Work.objects.filter(service_provider=profile)
                     if rating is not None:
                            rating = round(rating, 1)
                     booking_reviews = BookingReviews.objects.filter(service_provider=profile)
                     return render(request, 'myapp/provider_dashboard.html', context={'user': request.user, 'profile': profile, 'all_bookings': bookings, 'upcoming_booking': upcoming_booking, 'history': history , 'booking_reviews': booking_reviews, 'rating': rating , 'rejected': rejected, 'completed': completed, 'previous_work': previous_work    })
              elif request.user.is_customer:
                     profile = CustomerProfileModel.objects.filter(user=request.user).first()
                     bookings = Booking.objects.filter(customer=profile).select_related('service_provider')
                     upcoming_booking = bookings.filter(status__in=('pending', 'accept')).order_by('-booking_date')
                     history = bookings.filter(status__in=('complete','cancel','reject')).order_by('-booking_date')
                     booking_reviews = BookingReviews.objects.filter(customer=profile)
                     completed = bookings.filter(status='complete').count()
                     canceled = bookings.filter(status='cancel').count()
                     return render(request, 'myapp/customer_dashboard.html', context={ 'user': request.user, 'profile':profile ,'all_bookings': bookings, 'upcoming_booking': upcoming_booking, 'history': history, 'booking_reviews': booking_reviews, 'completed': completed, 'canceled': canceled})

       else:
              return redirect('mainapp:login')
       
@login_required
def CustomerProfile(request):
       print('CustomerProfile view accessed')
       CustomerProfile=CustomerProfileModel.objects.filter(user=request.user).first()
       print(CustomerProfile)
       if CustomerProfile is None:
              return redirect('mainapp:CustomerProfileEdit')
       return render (request ,'myapp/CustomerProfile.html', context={'profile': CustomerProfile , 'user': request.user})

@login_required
def ProviderProfile(request):
       print('ProviderProfile view accessed')
       ProviderProfile=ProviderProfileModel.objects.filter(user=request.user).first()
       if ProviderProfile is None:
              return redirect('mainapp:ProviderProfileEdit')  
       return render (request ,'myapp/ProviderProfile.html', context={'profile': ProviderProfile , 'user': request.user})


@login_required
def CustomerProfileEdit(request):
       profile ,created=CustomerProfileModel.objects.get_or_create(user=request.user)
       if request.method == 'POST':
              form = CustomerProfileForm(request.POST, request.FILES, instance=profile ,user=request.user)
              if form.is_valid():
                     profile.save()
                     if created:
                             messages.success(request, "Profile created successfully")
                     else:
                             messages.success(request, "Profile updated successfully")
                     return redirect('mainapp:CustomerProfile')
       else:
              form = CustomerProfileForm(instance=profile, user=request.user)
       return render(request, 'myapp/CustomerProfileEdit.html', context={'form': form ,'profile': profile })

@login_required
def ProviderProfileEdit(request):
       profile ,created=ProviderProfileModel.objects.get_or_create(user=request.user)
       if request.method == 'POST':
              form = ProviderProfileForm(request.POST, request.FILES, instance=profile ,user=request.user)
              if form.is_valid():
                     profile.save()
                     if created:
                             messages.success(request, "Profile created successfully")
                     else:
                             messages.success(request, "Profile updated successfully")
                     return redirect('mainapp:ProviderProfile')
       else:
              form = ProviderProfileForm(instance=profile, user=request.user)
       return render(request, 'myapp/ProviderProfileEdit.html', context={'form': form ,'profile': profile })


@login_required
def changepassword(request):
       if request.method == 'POST':
              form = ChangePasswordForm(request.POST, user=request.user)

myapp/templates/CustomerProfile.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="container profile-setion my-5 " >
  <div class="mx-auto text-center">
    <div
      class="rounded-circle mx-auto shadow"
      style="width: 200px; height: 200px; overflow: hidden"
    >
      <img src={% if profile.profileImage %} "{{ profile.profileImage.url }}"  {% else %} 
      "{% static 'local_service_images/serviceprovider2.jpeg' %}" {% endif %} 
      alt="profileimage" class="img-fluid h-100 w-100" style="object-fit:
      cover" >
    </div>
    <h4 class="mt-4 fw-semibold">{{ profile.username | default:"Customer Name" }}</h4>
    
  </div>
  <div class="mt-4 p-4 shadow rounded  bg-light" >
    <h3 class="mb-3 border-bottom pb-2">Contact Information</h3>

    <div class="mb-3">
      <strong>Email:</strong>
      <p class="mb-0 text-muted">{{ profile.user.email | default:"sample@gmail.com" }}</p>
    </div>

    <div class="mb-3">
      <strong>Phone No:</strong>
      <p class="mb-0 text-muted">{{ profile.mobile_no | default:"+91 8907654321" }}</p>
    </div>

    <div class="mb-3">
      <strong>Address:</strong>
      <p class="mb-0 text-muted">
        {{ profile.address | default:"1234 Street Name, City, State, Zip" }}
      </p>
    </div>
  </div>
  <!-- Buttons -->
  <div class="d-flex gap-5 mt-5 ">
    <!-- Button to trigger Change Password Modal -->
    <button
      class="btn edit rounded-pill px-4"
      data-bs-toggle="modal"
      data-bs-target="#ChangePasswordModal"
    >
      Change Password
    </button>

    <!-- Edit Profile Button -->

    <a
      href="{% url 'mainapp:CustomerProfileEdit' %}"
      class="btn edit  rounded-pill px-4"
      >Edit Profile</a
    >
  </div>

  <!-- Change Password Modal -->
  <div class="modal fade" id="ChangePasswordModal">
    <div class="modal-dialog">
      <div class="modal-content rounded-5 shadow p-3">
        <div class="modal-header border-0">
          <h5 class="modal-title" id="ChangePasswordModalLabel">
            Change Password
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
          ></button>
        </div>
        <form method="POST" action="{% url 'mainapp:changepassword' %}">
          {% csrf_token %}
          <div class="modal-body">
            {% include "include/error.html" %}
            <div class="mb-3">
              <label for="old_Password" class="form-label">Old Password</label>
              <input
                type="password"
                class="form-control rounded-3"
                id="old_Password"
                name="old_password"
                placeholder="Enter old password"
                required
              />
            </div>
            <div class="mb-3">
              <label for="new_Password" class="form-label">New Password</label>
              <input
                type="password"
                class="form-control rounded-3"
                id="new_Password"
                name="new_password"
                placeholder="Enter new password"
                required
              />
            </div>
            <div class="mb-3">
              <label for="confirm_new_Password" class="form-label"
                >Confirm New Password</label
              >
              <input
                type="password"
                class="form-control rounded-3"
                id="confirm_new_Password"
                name="confirm_new_password"
                placeholder="Re-enter new password"
                required
              />
            </div>
          </div>
          <div class="modal-footer border-0 d-flex justify-content-between">
            <button
              type="button"
              class="btn btn-outline-secondary rounded-pill px-4"
              data-bs-dismiss="modal"
            >
              Cancel
            </button>
            <button type="submit" class="btn btn-primary rounded-pill px-4">
              Update Password
            </button>
          </div>
        </form>
      </div>
    </div>
    ``
  </div>
</section>

<section class="modal fade" id="messageModal">
  <div class="modal-dialog">
    <div class="modal-body">
      <div class="text-center">
        {% for message in messages %}
        <h5 class="alert alert-{{ message.tags }} ">{{ message }}</h5>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
{% if messages %}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Show the modal if there are  messages
    var messageModal = new bootstrap.Modal(
      document.getElementById("messageModal")
    );
    messageModal.show();
  });
</script>
{% endif %} {% if form.errors %}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Show the modal if there are errors or messages
    var changePasswordModal = new bootstrap.Modal(
      document.getElementById("ChangePasswordModal")
    );
    changePasswordModal.show();
  });
</script>
{% endif %} {% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <!--  Font Awesome for star icons -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- css link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <!-- header-->
    {% include "include/header.html" %} {% block content %}
   
    <!-- main content -->
    {% endblock %} {% include "include/footer.html" %}

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myapp/templates/login.html
{% extends "base2.html" %} {% block content %}

<section class="container login-section">
  <div class="row justify-content-center">
    <div class="col-10 col-md-6 col-lg-5">
      <div class=" p-1 p-sm-3 shadow rounded bg-white mt-2 mt-md-5">
        <h2 class="text-center my-3">Login Your Account</h2>
        {% include "include/error.html" %}
        <div class="p-4 pt-0">
          <form method="POST" class="form-container"  action="{% url 'mainapp:login' %}">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Username</label>
              <input
                type="text"
                name="username"
                id="username"
                class="form-control"
                placeholder="Enter your username"
                required
              />
            </div>

            <div class="mb-3">
              <label for="password" class="form-label">Password</label>
              <input
                type="password"
                name="password"
                id="password"
                class="form-control"
                placeholder="Enter your password"
                required
              />
            </div>

            <div class="d-flex justify-content-between align-items-center mb-3">
              <button type="submit" class="btn btn-primary d-flex align-items-center justify-content-center">Login</button>
              <button
                type="button"
                data-bs-toggle="modal"
                data-bs-target="#forgotpassword"
                style="all: unset; cursor: pointer"
              >
                forgotpassword
              </button>
            </div>
          </form>
          <div class="d-flex align-items-center my-3">
            <hr class="flex-grow-1" />
            <span class="mx-2 text-muted">or</span>
            <hr class="flex-grow-1" />
          </div>
          <div class="text-center mt-3">
            <a
              href="{% url 'mainapp:register' %}"
              class="btn btn-outline-secondary"
              >Create your account</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <!-- Button trigger modal -->

    <!-- Modal -->
    <div class="modal fade" id="forgotpassword">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Forgot Password</h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
            ></button>
          </div>

          <div class="modal-body">
            <form method="POST" class="border-0" action="{% url 'mainapp:forgotpassword' %}">
              {% csrf_token %}
              <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  placeholder="Enter your registered email"
                  class="form-control"
                  required
                />
              </div>

              <p class="mt-4 text-center text-muted">
                We have sent a password reset link to your registered email
                address.
              </p>

              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary pb-2 d-flex align-items-center justify-content-center"
                  data-bs-dismiss="modal"
                >
                  Close
                </button>
                <button type="submit" class="btn btn-primary d-flex align-items-center justify-content-center">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

myapp/templates/service.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="service-section container-fluid ">
  <div class="row">
    <div class="col-lg-4 col-xl-3 p-3 nav-side bg-light pl pt-5 d-none d-lg-block">
      <h2>Filter your service</h2>
      <form action="{% url 'mainapp:service' %}" class="filter-form m-3" method="GET">
        <div class="mb-3">
          <label for="location" class="form-label mb-3">Location</label>
          <input
            type="text"
            id="location"
            name="location"
            class="form-control"
            value="{{ filter_items.location|default:'' }}"
          />
        </div>
        
        <div class="mb-3">
          <label for="category" class="form-label mb-2">Category</label>
          <select name="category" id="category" class="form-control mb-2">
            <option value='' >Select Category</option>
            <option value="plumbing" {% if filter_items.category == "plumbing" %} selected {% endif %}>Plumbing</option>
            <option value="electrical" {% if filter_items.category == "electrical" %} selected {% endif %}>Electrical</option>
            <option value="cleaning" {% if filter_items.category == "cleaning" %} selected {% endif %}>Cleaning</option>
            <option value="carpentry" {% if filter_items.category == "carpentry" %} selected {% endif %}>Carpentry</option>
            <option value="gardening" {% if filter_items.category == "gardening" %} selected {% endif %}>Gardening</option>
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label mb-2">Rating</label>
          {% for i in "54321" %}
          <div class="form-check m-2">
            <input
              type="radio"
              name="rating"
              value="{{ i }}"
              id="rating{{ i }}"
              class="form-check-input"
              {% if filter_items.rating == i %} checked {% endif %}
            />
            <label for="rating{{ i }}" class="form-check-label">{{ i }} Stars & up</label>
          </div>
         {% endfor %}
        
        </div>
        <div class="mb-3">
          <button type="submit" class="btn btn-primary">Apply filter</button>
        </div>
      </form>
    </div>
    <div class="col-lg-7 col-xl-8 ms-3 p-3  pt-5 ">
      <div class="d-flex justify-content-between align-items-center service-header">
      <h2>Find Trusted Services</h2>
      <button class=" btn btn-outline-primary d-block d-lg-none me-3" data-bs-toggle="offcanvas" data-bs-target="#serviceFilter" >☰ Filter Services</button>
      </div>
      {% if page_obj %}
      {% for service in page_obj %}
      <div class="service-list mt-5">
        <!-- Service items will be dynamically inserted here -->
       
        <div class="service-item row g-3">
          <div class="service_provider_image col-5  col-md-3 col-lg-3 ">
            <img
              src="{{ service.profileImage.url }}"
              alt="Service Provider image"
              class="img-fluid rounded-circle m-0 p-0 "
              style='height: 150px; width: 150px;'
            />
          </div>

          <div class="service_provider_details col-6 col-md-5 col-lg-5 align-self-center ms-3">
            <h5>{{ service.service_name }}</h5>
            <h6>Name : {{ service.username }}</h6>
            <p>Location :{{ service.city }} <br />
              {% for i in "12345" %}
               {% if forloop.counter <= service.average_rating.rating %}
                    <span style="color: gold; font-size: 22px;">&#9733;</span>
                {% else %}
                    <span style="color: lightgray; font-size: 22px;">&#9733;</span>
               {% endif %}
              {% endfor %}
            </p>
            <div class="service_provider_actions  d-flex align-items-center justify-content-start  d-md-none ">
            <a
              href="{% url 'mainapp:providerdetails' provider_slug=service.slug %}"
              class="btn btn-primary">View details</a>
          </div>
          </div>
          <div
            class="service_provider_actions d-none d-md-flex align-items-center justify-content-end  col-md-3"
          >
            <a
              href="{% url 'mainapp:providerdetails' provider_slug=service.slug %}"
              class="btn btn-primary"
              >View details</a
            >
          </div>
        </div>
      </div>
      <hr />
      {% endfor %}
      <ul class="pagination">
       {% if page_obj.has_previous %}
       <li class='page-item'><a href="?page=1" class='page-link'> &laquo;first</a></li>
       <li class='page-item'><a href="?page={{ page_obj.previous_page_number }}" class='page-link'>{{ page_obj.previous_page_number }}</a></li>
       {% endif %}

       <li class='page-item'><a href="?page={{ page_obj.number }}" class='page-link'> page{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>

       {% if page_obj.has_next %}
       <li class='page-item'><a href="?page={{ page_obj.next_page_number }}" class='page-link'>{{ page_obj.next_page_number }}</a></li>
       <li class='page-item'><a href="?page={{ page_obj.paginator.num_pages }}" class='page-link'>last &raquo;</a></li>
       {% endif %}
      </ul>
      {% else %}
      <p>there is no service provider in this area</p>
      {% endif %}

    </div>
  </div>

 <!-- offcanvas -->

 <div class='offcanvas offcanvas-start ' data-bs-scroll="true" tabindex='-1' id='serviceFilter' >
   <div class='offcanvas-header'>
     <h5 class='offcanvas-title' >Filter Services</h5>
     <button type='button' class='btn-close' data-bs-dismiss='offcanvas' ></button>
   </div>
   <div class='offcanvas-body'>
      <form action="{% url 'mainapp:service' %}" class="filter-form m-3" method="GET">
        <div class="mb-3"> 
          <label for="location" class="form-label mb-3">Location</label>
          <input
            type="text"
            id="location"
            name="location"
            class="form-control"
            value="{{ filter_items.location|default:'' }}"
          />
        </div>
        
        <div class="mb-3">
          <label for="category" class="form-label mb-2">Category</label>
          <select name="category" id="category" class="form-control mb-2">
            <option value='' >Select Category</option>
            <option value="plumbing" {% if filter_items.category == "plumbing" %} selected {% endif %}>Plumbing</option>
            <option value="electrical" {% if filter_items.category == "electrical" %} selected {% endif %}>Electrical</option>
            <option value="cleaning" {% if filter_items.category == "cleaning" %} selected {% endif %}>Cleaning</option>
            <option value="carpentry" {% if filter_items.category == "carpentry" %} selected {% endif %}>Carpentry</option>
            <option value="gardening" {% if filter_items.category == "gardening" %} selected {% endif %}>Gardening</option>
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label mb-2">Rating</label>
          {% for i in "54321" %}
          <div class="form-check m-2">
            <input
              type="radio"
              name="rating"
              value="{{ i }}"
              id="rating{{ i }}"
              class="form-check-input"
              {% if filter_items.rating == i %} checked {% endif %}
            />
            <label for="rating{{ i }}" class="form-check-label">{{ i }} Stars & up</label>
          </div>
         {% endfor %}
        
        </div>
        <div class="mb-3">
          <button type="submit" class="btn btn-primary">Apply filter</button>
        </div>
      </form>
   </div>
 </div>

</section>



{% endblock content %}